name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "11 11 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "755365600@qq.com"
          git config --local user.name "butcherl7"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Sometimes things have to fall apart to make way for better things."
          git push
