name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "27 9 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "755365600@qq.com"
          git config --local user.name "kinglyq"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "One minute on the stage needs ten years practice off stage."
          git push
